package com.prudentgaming.betting.model;

import java.math.BigInteger;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import java.io.Serializable;

@Data // lombok annotation for generating getter-setters-toString-hashcode-equals methods
@Entity // denoting this is a JPA entity object
@Table(name = "betting_data") // denoting which table this class should be mapped to
public class Bet implements Serializable{
	
	// Column name of the database column given field should be mapped to
	// JsonProperty represnt the name of the JSON key during serialization/deserialization

	@GeneratedValue(strategy = GenerationType.AUTO)
	@Id // primary key of the table which is autogenerated
	@Column(name = "bet_uid")
	@JsonProperty("bet_uid")
	private BigInteger betUid;
	
	@Column(name = "id") 
	@JsonProperty("id") 
	private Integer id;

	@Column(name = "total_bets") 
	@JsonProperty("numbets") 
	private Integer totalBets;

	@Column(name = "client_id") 
	@JsonProperty("clientid") 
	private Integer clientId;

	@Column(name = "game") 
	@JsonProperty("game") 
	private String game;
	
	@Column(name = "stake") 
	@JsonProperty("stake") 
	private double stake;
	
	@Column(name = "total_returns") 
	@JsonProperty("returns") 
	private double totalReturns;

	@Column(name = "game_date") 
	@JsonProperty("date") 
	private Date gameDate;

}
